// Import createSlice from Redux Toolkit for creating a slice of the Redux store
import { createSlice } from "@reduxjs/toolkit";

// Define the type for the state
interface ticTacToeState {
  value: boolean;
}

// Create a slice using createSlice
const ticTacToeSlice = createSlice({
  name: "ticTacToe", // Name of the slice, used as the key in the root reducer
  initialState: { value: false } as ticTacToeState, // Initial state for this slice
  reducers: {
    setTıcTacToeOpen: (state) => {
      // Toggle the boolean value when setOpen is dispatched
      state.value = !state.value;
      console.log(`TicTacToe open state is set ${state.value}`);
    },
  },
});

// Export the increment and decrement action creators for dispatching the corresponding actions
export const { setTıcTacToeOpen } = ticTacToeSlice.actions;

// Export the reducer function generated by createSlice as the default export of this module
const ticTacToeReducer = ticTacToeSlice.reducer;
export default ticTacToeReducer;
