// Import createSlice from Redux Toolkit for creating a slice of the Redux store
import { createSlice } from "@reduxjs/toolkit";

// Define the type for the state
interface welcomeState {
  value: boolean;
}

// Create a slice using createSlice
const welcomeSlice = createSlice({
  name: "welcome", // Name of the slice, used as the key in the root reducer
  initialState: { value: true } as welcomeState, // Initial state for this slice
  reducers: {
    setWelcomeOpen: (state) => {
      // Toggle the boolean value when setOpen is dispatched
      state.value = !state.value;
      console.log(`Welcome open state is set ${state.value}`);
    },
  },
});

// Export the increment and decrement action creators for dispatching the corresponding actions
export const { setWelcomeOpen } = welcomeSlice.actions;

// Export the reducer function generated by createSlice as the default export of this module
const welcomeReducer = welcomeSlice.reducer;
export default welcomeReducer;
